In [1]:
#--basics of torch tensors

In [2]:
import torch

print(torch.__version__)

2.0.1+cu118


In [3]:
import numpy as np

In [4]:
l=[1,2,3,4,5]

#--convert list to array
arr=np.array(l)
arr

array([1, 2, 3, 4, 5])

In [6]:
#--convert numpy array to tensor
t1=torch.from_numpy(arr)
t2=torch.tensor(arr)

print(t1)
print(t2)

tensor([1, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])


In [7]:
t1[0]=2

In [8]:
print(arr)
print(t1)
print(t2)

[2 2 3 4 5]
tensor([2, 2, 3, 4, 5])
tensor([1, 2, 3, 4, 5])


In [9]:
a=torch.tensor([1,2,3,4],dtype=torch.int32)
b=torch.tensor([1,1,1,1],dtype=torch.int32)

In [10]:
c=torch.add(a,b)
c

tensor([2, 3, 4, 5], dtype=torch.int32)

In [11]:
d=torch.matmul(a,b)
d

tensor(10, dtype=torch.int32)

In [14]:
a=torch.ones((3,2,3),dtype=torch.int32)
a

tensor([[[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]],

        [[1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)

In [18]:
#--torch backpropagation

In [32]:
#--y=x**2
x=torch.tensor(3.0,requires_grad=True)
x

tensor(3., requires_grad=True)

In [33]:
y=x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [34]:
# y.backward()

In [35]:
# x.grad

In [36]:
z=y**2+x
z

tensor(84., grad_fn=<AddBackward0>)

In [37]:
z.backward()


In [38]:
y

tensor(9., grad_fn=<PowBackward0>)

In [40]:
x.grad

tensor(109.)