In [1]:
#--train simple linear regression model for crop predictions

In [2]:
#--import libraries

import torch
import numpy as np

In [ ]:
#--prepare dataset in numpy

inputs=np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70]
],
dtype="float32"
)

inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [ ]:
targets= np.array([
    [56],
    [81],
    [119],
    [22],
    [103]
],
                 dtype="float32")
targets

array([[ 56.],
       [ 81.],
       [119.],
       [ 22.],
       [103.]], dtype=float32)

In [ ]:
#--convert into tensors
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [ ]:
#---define random weights and bias
#---x=[5,3]
#---w=[1,3]
#---b=[1,1]
#---y=x * w.T + b

w=torch.randn(1,3,requires_grad=True)
b=torch.randn(1,requires_grad=True)

print(w)
print(b)

tensor([[ 0.2513, -0.1943, -0.1971]], requires_grad=True)
tensor([-0.3349], requires_grad=True)


In [ ]:
#--define model
def model(x):
  return x @ w.t() + b

In [ ]:
#--generate predictions/forward pass
preds=model(inputs)
print(preds)

tensor([[ -3.4891],
        [ -7.1866],
        [-15.9492],
        [  9.6445],
        [-15.4517]], grad_fn=<AddBackward0>)


In [ ]:
#---mse loss
def mse(t1,t2):
  diff=t1-t2
  return  torch.sum(diff*diff/diff.numel())

In [ ]:
loss=mse(preds,targets)
print(loss)
#--compute gradients
loss.backward()
#--gradients for weights
print(w)
print(w.grad)

tensor(8742.1162, grad_fn=<SumBackward0>)
tensor([[ 0.2513, -0.1943, -0.1971]], requires_grad=True)
tensor([[-13416.6787, -16692.8145,  -9911.1201]])


In [ ]:
#--adjust weights and reset gradients
with torch.no_grad():
  w-=1e-5*w.grad
  b-=1e-5*b.grad
  print(w)
  print(b)
  w.grad.zero_()
  b.grad.zero_()

tensor([[ 0.3854, -0.0274, -0.0980]], requires_grad=True)
tensor([-0.3332], requires_grad=True)


In [ ]:
#--calculate loss again
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(4166.1021, grad_fn=<SumBackward0>)


In [ ]:
#---training for multiple epochs
epochs=100
for i in range(epochs):
  preds=model(inputs)
  loss=mse(preds,targets)
  print(" loss :",i,loss)
  loss.backward()

  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

 loss : 0 tensor(4166.1021, grad_fn=<SumBackward0>)
 loss : 1 tensor(2267.3193, grad_fn=<SumBackward0>)
 loss : 2 tensor(1471.6912, grad_fn=<SumBackward0>)
 loss : 3 tensor(1130.8141, grad_fn=<SumBackward0>)
 loss : 4 tensor(977.5880, grad_fn=<SumBackward0>)
 loss : 5 tensor(901.9801, grad_fn=<SumBackward0>)
 loss : 6 tensor(858.6581, grad_fn=<SumBackward0>)
 loss : 7 tensor(828.9401, grad_fn=<SumBackward0>)
 loss : 8 tensor(805.1239, grad_fn=<SumBackward0>)
 loss : 9 tensor(784.0284, grad_fn=<SumBackward0>)
 loss : 10 tensor(764.3366, grad_fn=<SumBackward0>)
 loss : 11 tensor(745.4982, grad_fn=<SumBackward0>)
 loss : 12 tensor(727.2804, grad_fn=<SumBackward0>)
 loss : 13 tensor(709.5798, grad_fn=<SumBackward0>)
 loss : 14 tensor(692.3478, grad_fn=<SumBackward0>)
 loss : 15 tensor(675.5577, grad_fn=<SumBackward0>)
 loss : 16 tensor(659.1920, grad_fn=<SumBackward0>)
 loss : 17 tensor(643.2381, grad_fn=<SumBackward0>)
 loss : 18 tensor(627.6840, grad_fn=<SumBackward0>)
 loss : 19 tensor(

In [3]:
#--train a linear regression with torch built-in
import torch.nn as nn

In [20]:
#--define inputs and targets
inputs=np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70]
], dtype='float32')

targets=np.array([
    [56, 70],
    [81, 101],
    [119, 133],
    [22, 37],
    [103, 119]
],dtype='float32')

#--convert them into tensors
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [21]:
#--prepare tensor combined dataset
from torch.utils.data import TensorDataset

train_df=TensorDataset(inputs,targets)
print(train_df)
print(train_df[:2])


(tensor([[73., 67., 43.],
        [91., 88., 64.]]), tensor([[ 56.,  70.],
        [ 81., 101.]]))


In [22]:
#--split data into batches
from torch.utils.data import DataLoader

batch_size=2
train_dl=DataLoader(train_df,batch_size,shuffle=True)

In [23]:
#--iterrate through each batch with for loop
for xb,yb in train_dl:
  print(xb)
  print(yb)

tensor([[ 73.,  67.,  43.],
        [ 87., 134.,  58.]])
tensor([[ 56.,  70.],
        [119., 133.]])
tensor([[102.,  43.,  37.],
        [ 91.,  88.,  64.]])
tensor([[ 22.,  37.],
        [ 81., 101.]])
tensor([[69., 96., 70.]])
tensor([[103., 119.]])


In [24]:
#--define linear model -> no need to define weights and bias separately
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)


Parameter containing:
tensor([[ 0.0491,  0.2421,  0.1138],
        [-0.1090,  0.1609,  0.4811]], requires_grad=True)
Parameter containing:
tensor([ 0.5157, -0.3220], requires_grad=True)


In [25]:
#--no need to add activation function because its a linear regression problem
#--parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0491,  0.2421,  0.1138],
         [-0.1090,  0.1609,  0.4811]], requires_grad=True),
 Parameter containing:
 tensor([ 0.5157, -0.3220], requires_grad=True)]

In [26]:
#--generate predictions
preds=model(inputs)
print(preds)

tensor([[25.2176, 23.1920],
        [33.5759, 34.7130],
        [43.8342, 39.6644],
        [20.1494, 13.2831],
        [35.1142, 41.2844]], grad_fn=<AddmmBackward0>)


In [27]:
#--loss function -> use in-built loss function
import torch.nn.functional as F
loss_fn=F.mse_loss
print(loss_fn)

<function mse_loss at 0x7d3df02b2680>


In [28]:
#--check loss for inputs
loss=loss_fn(preds,targets)
print(loss)

tensor(3535.7090, grad_fn=<MseLossBackward0>)


In [29]:
#--optimizer -> use in-built optimizer
opt=torch.optim.SGD(model.parameters(),lr=1e-5)
print(opt)

SGD (
Parameter Group 0
    dampening: 0
    differentiable: False
    foreach: None
    lr: 1e-05
    maximize: False
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [34]:
#--train the model
#--pass the inputs to get predictions
#--compute loss
#--compute gradients
#--update the weights
#--reset the gradients

def fit(num_epochs,model,loss_fn,opt,train_dl):
  #--repeat for each epoch
  for epoch in range(num_epochs):

    #--iterations -> pass each batch
    for xb,yb in train_dl:

      #--get the predictions
      preds=model(xb)

      #--compute loss
      loss=loss_fn(preds,yb)

      #--compute gradients
      loss.backward()

      #--update the weights and bias
      opt.step()

      #--reset the gradients to zero
      opt.zero_grad()

    #--print loss for every 10th epoch
    if (epoch+1)%10 ==0:
      print('Epoch [{}/{}] , Loss : {:.4f}'.format(epoch+1,num_epochs,loss))

In [35]:
#--train the model
fit(100,model,loss_fn,opt,train_dl)

Epoch [10/100] , Loss : 35.1167
Epoch [20/100] , Loss : 1.7804
Epoch [30/100] , Loss : 8.1052
Epoch [40/100] , Loss : 6.5779
Epoch [50/100] , Loss : 3.5112
Epoch [60/100] , Loss : 3.1265
Epoch [70/100] , Loss : 0.8278
Epoch [80/100] , Loss : 5.8944
Epoch [90/100] , Loss : 1.3165
Epoch [100/100] , Loss : 1.8671


In [36]:
#--generate predictions with trained model
preds=model(inputs)
print(preds)
print(targets)

tensor([[ 57.6294,  70.5086],
        [ 80.7998, 100.0631],
        [121.6486, 134.4704],
        [ 22.7093,  38.0535],
        [ 98.5878, 117.3797]], grad_fn=<AddmmBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
