In [1]:
#--train simple linear regression model for crop predictions

In [2]:
#--import libraries

import torch
import numpy as np

In [37]:
#--prepare dataset in numpy

inputs=np.array([
    [73, 67, 43],
    [91, 88, 64],
    [87, 134, 58],
    [102, 43, 37],
    [69, 96, 70]
],
dtype="float32"
)

inputs

array([[ 73.,  67.,  43.],
       [ 91.,  88.,  64.],
       [ 87., 134.,  58.],
       [102.,  43.,  37.],
       [ 69.,  96.,  70.]], dtype=float32)

In [38]:
targets= np.array([
    [56],
    [81],
    [119],
    [22],
    [103]
],
                 dtype="float32")
targets

array([[ 56.],
       [ 81.],
       [119.],
       [ 22.],
       [103.]], dtype=float32)

In [39]:
#--convert into tensors
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [46]:
#---define random weights and bias
#---x=[5,3]
#---w=[1,3]
#---b=[1,1]
#---y=x * w.T + b

w=torch.randn(1,3,requires_grad=True)
b=torch.randn(1,requires_grad=True)

print(w)
print(b)

tensor([[ 0.2513, -0.1943, -0.1971]], requires_grad=True)
tensor([-0.3349], requires_grad=True)


In [47]:
#--define model
def model(x):
  return x @ w.t() + b

In [48]:
#--generate predictions/forward pass
preds=model(inputs)
print(preds)

tensor([[ -3.4891],
        [ -7.1866],
        [-15.9492],
        [  9.6445],
        [-15.4517]], grad_fn=<AddBackward0>)


In [49]:
#---mse loss
def mse(t1,t2):
  diff=t1-t2
  return  torch.sum(diff*diff/diff.numel())

In [50]:
loss=mse(preds,targets)
print(loss)
#--compute gradients
loss.backward()
#--gradients for weights
print(w)
print(w.grad)

tensor(8742.1162, grad_fn=<SumBackward0>)
tensor([[ 0.2513, -0.1943, -0.1971]], requires_grad=True)
tensor([[-13416.6787, -16692.8145,  -9911.1201]])


In [51]:
#--adjust weights and reset gradients
with torch.no_grad():
  w-=1e-5*w.grad
  b-=1e-5*b.grad
  print(w)
  print(b)
  w.grad.zero_()
  b.grad.zero_()

tensor([[ 0.3854, -0.0274, -0.0980]], requires_grad=True)
tensor([-0.3332], requires_grad=True)


In [52]:
#--calculate loss again
preds=model(inputs)
loss=mse(preds,targets)
print(loss)

tensor(4166.1021, grad_fn=<SumBackward0>)


In [53]:
#---training for multiple epochs
epochs=100
for i in range(epochs):
  preds=model(inputs)
  loss=mse(preds,targets)
  print(" loss :",i,loss)
  loss.backward()

  with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

 loss : 0 tensor(4166.1021, grad_fn=<SumBackward0>)
 loss : 1 tensor(2267.3193, grad_fn=<SumBackward0>)
 loss : 2 tensor(1471.6912, grad_fn=<SumBackward0>)
 loss : 3 tensor(1130.8141, grad_fn=<SumBackward0>)
 loss : 4 tensor(977.5880, grad_fn=<SumBackward0>)
 loss : 5 tensor(901.9801, grad_fn=<SumBackward0>)
 loss : 6 tensor(858.6581, grad_fn=<SumBackward0>)
 loss : 7 tensor(828.9401, grad_fn=<SumBackward0>)
 loss : 8 tensor(805.1239, grad_fn=<SumBackward0>)
 loss : 9 tensor(784.0284, grad_fn=<SumBackward0>)
 loss : 10 tensor(764.3366, grad_fn=<SumBackward0>)
 loss : 11 tensor(745.4982, grad_fn=<SumBackward0>)
 loss : 12 tensor(727.2804, grad_fn=<SumBackward0>)
 loss : 13 tensor(709.5798, grad_fn=<SumBackward0>)
 loss : 14 tensor(692.3478, grad_fn=<SumBackward0>)
 loss : 15 tensor(675.5577, grad_fn=<SumBackward0>)
 loss : 16 tensor(659.1920, grad_fn=<SumBackward0>)
 loss : 17 tensor(643.2381, grad_fn=<SumBackward0>)
 loss : 18 tensor(627.6840, grad_fn=<SumBackward0>)
 loss : 19 tensor(